variables:
-   value: 17.0.5_8
    options: null
    expand: null
    description: null
    key: JAVA_VERSION
-   options: null
    description: null
    key: SBT_VERSION
    value: 1.8.2
    expand: null
-   expand: null
    options: null
    value: 2.13.10
    description: null
    key: SCALA_VERSION
-   description: null
    expand: null
    options: null
    value: eclipse-temurin-${JAVA_VERSION}_${SBT_VERSION}_${SCALA_VERSION}
    key: SCALA_SBT_IMAGE_VERSION
default: null
include: null
workflow: null
jobs:
-   name: publish
    service: null
    before_script: null
    id_tokSens: null
    only:
        refs:
        - ' - master'
        kubernetes: null
        variables: null
        changes: null
    artifacts: null
    rules: null
    hooks: null
    retry: null
    stage: build
    trigger: null
    when: null
    needs: null
    dependencies: null
    dast_configuration: null
    variables: null
    extends_1: null
    timeout: null
    release: null
    coverage: null
    except: null
    cache: null
    image:
        name: sbtscala/scala-sbt:$SCALA_SBT_IMAGE_VERSION
        entrypoint: ''
        pull_policy: null
    tags: null
    interruptible: null
    allow_failure: true
    parallel: null
    inherit: null
    script:
    - '- sbt -mem 2048 scalafmtCheckAll'
    after_script: null
    environment: null
-   cache: null
    service: null
    before_script: null
    dast_configuration: null
    trigger: null
    script:
    - '- sbt -mem 2048 scalafmtCheckAll'
    needs: null
    name: scalafmt_branches
    dependencies: null
    id_tokSens: null
    parallel: null
    hooks: null
    release: null
    inherit: null
    after_script: null
    timeout: null
    only: null
    rules: null
    allow_failure: true
    image:
        name: sbtscala/scala-sbt:$SCALA_SBT_IMAGE_VERSION
        entrypoint: ''
        pull_policy: null
    tags: null
    except:
        refs:
        - '- master'
        - '- tags'
        kubernetes: null
        variables: null
        changes: null
    variables: null
    stage: compile
    interruptible: null
    environment: null
    coverage: null
    retry: null
    when: null
    extends_1: null
    artifacts: null
-   parallel: null
    when: null
    id_tokSens: null
    timeout: null
    variables: null
    rules: null
    script:
    - '- sbt -mem 2048 scalafmtCheckAll'
    retry: null
    service: null
    extends_1: null
    interruptible: null
    image:
        name: sbtscala/scala-sbt:$SCALA_SBT_IMAGE_VERSION
        entrypoint: ''
        pull_policy: null
    hooks: null
    after_script: null
    coverage: null
    release: null
    tags: null
    name: scalafmt_master
    allow_failure: true
    before_script: null
    dependencies: null
    trigger: null
    artifacts: null
    stage: build
    except: null
    needs: null
    only:
        refs:
        - ' - master'
        kubernetes: null
        variables: null
        changes: null
    inherit: null
    dast_configuration: null
    environment: null
    cache: null
stages:
- '- compile'
- '- build'
